### ISSUE TITLE
Gaussian Elliptical Solution Failed

### ISSUE THREAD

**Issue by aishrimc** [OxfordSKA/OSKAR#13]
I am trying to run OSKAR 2.7.1 using a sky catalog that contains around 1450 sources, and I have arranged the source catalog exactly as the sample "sky.osm"  file included in the example simulations. However for every run I am doing it is showing "WARNING: Gaussian ellipse solution failed for 1429 sources. These will be simulated as point sources", and the imaging procedure is subsequently failing to show any of the extended structures in the field. I tried by reducing the number of sources to just 10 sources with the same result. 
Can you kindly suggest some cause for this? And any changes that I need to do in my simulation?  
Thanks...

**Comment by fdulwich** [comment]
I think this was resolved offline as a units error in the sky model file, so I will close this issue now.
