### ISSUE TITLE
Method to input diffuse radiation

### ISSUE THREAD

**Issue by aishrimc** [OxfordSKA/OSKAR#16]
Is there a way to input diffuse radiation? The GSM data file produced from the software obtained from [http://space.mit.edu/angelica/gsm/]() cannot be obtained since it is showing 

> The content you were looking for could not be found

**Comment by fdulwich** [comment]
Thanks for pointing this out - it seems that the Global Sky Model page no longer exists, so I will remove this from OSKAR as well. You could try using FITS files (either regular of HEALPix) to represent diffuse emission, but be aware that OSKAR will treat each pixel as a compact source, so make sure the pixel separation is sufficiently small if you want these to remain unresolved by the telescope.
