### ISSUE TITLE
MS antenna positions should be absolute

### ISSUE THREAD

**Issue by tammojan** [OxfordSKA/OSKAR#20]
When exporting to MeasurementSet, the antenna positions seem to be given in the ITRF frame relative to the array center. This is incorrect (or at least unusual), the column ANTENNA::POSITION should contain ITRF locations of the station centers in an absolute way. Could be fixed by just adding the coordinates of the array center.

**Comment by fdulwich** [comment]
So far this hasn't affected our ability to analyse simulated data as we've only needed (u,v,w) coordinates, so it's been some way down the list of priorities. I can do a fix if it will be helpful though.

**Comment by fdulwich** [comment]
Sorry this took quite a while, but it should be fixed now.
