### ISSUE TITLE
Unit Tests failing after successful installation of latest version

### ISSUE THREAD

**Issue by aishrimc** [OxfordSKA/OSKAR#21]
I have installed the latest version in a CentOS 7 machine. There was no error during installation, but on running `ctest [--verbose]` the output is :
`Test project /home/newuser/OSKAR/build`
      `Start  1: binary_test`
` 1/13 Test  #1: binary_test ......................***Failed    0.00 sec`
     ` Start  2: settings_test`
` 2/13 Test  #2: settings_test ....................   Passed    0.01 sec`
      Start  3: convert_test
 `3/13 Test  #3: convert_test .....................***Failed    0.07 sec`
    `  Start  4: correlate_test`
 `4/13 Test  #4: correlate_test ...................***Failed    0.23 sec`
      `Start  5: imager_test`
 `5/13 Test  #5: imager_test ......................   Passed    0.92 sec`
      Start  6: jones_test
 `6/13 Test  #6: jones_test .......................***Failed    0.16 sec`
     ` Start  7: math_test`
 `7/13 Test  #7: math_test ........................***Exception: SegFault  2.24 sec`
     ` Start  8: mem_test`
` 8/13 Test  #8: mem_test .........................***Failed    0.10 sec`
     ` Start  9: sky_test`
 `9/13 Test  #9: sky_test .........................***Exception: SegFault  0.33 sec`
    `  Start 10: station_test`
`10/13 Test #10: station_test .....................***Exception: SegFault  0.15 sec`
      `Start 11: telescope_test`
`11/13 Test #11: telescope_test ...................***Exception: SegFault  0.16 sec`
      `Start 12: utility_test`
`12/13 Test #12: utility_test .....................***Failed    0.09 sec`
     ` Start 13: vis_test`
`13/13 Test #13: vis_test .........................***Failed    0.05 sec`

`15% tests passed, 11 tests failed out of 13`

`Total Test time (real) =   4.53 sec`

`The following tests FAILED:
	  1 - binary_test (Failed)
	  3 - convert_test (Failed)
	  4 - correlate_test (Failed)
	  6 - jones_test (Failed)
	  7 - math_test (SEGFAULT)
	  8 - mem_test (Failed)
	  9 - sky_test (SEGFAULT)
	 10 - station_test (SEGFAULT)
	 11 - telescope_test (SEGFAULT)
	 12 - utility_test (Failed)
	 13 - vis_test (Failed)
Errors while running CTest`

Also, the command `$ oskar` yeilds `bash: oskar: command not found...`

**Comment by fdulwich** [comment]
Since almost everything fails, I'm guessing this might be a permissions issue. Does the user running ctest have permission to write files to the build directory? Check also that you have write permission at the install location. It might be worth checking that that location is in the PATH environment variable.

**Comment by aishrimc** [comment]
The installation was done as sudoer. Hence I modified the directory permissions using  `sudo chmod -R 757 /home/newuser/OSKAR/`.  But even with write permission, some tests are failing. Now `ctest [--verbose]`  yeilds : 
```
Test project /home/newuser/OSKAR/build
      Start  1: binary_test
 1/13 Test  #1: binary_test ......................   Passed    0.00 sec
      Start  2: settings_test
 2/13 Test  #2: settings_test ....................   Passed    0.01 sec
      Start  3: convert_test
 3/13 Test  #3: convert_test .....................***Failed    0.07 sec
      Start  4: correlate_test
 4/13 Test  #4: correlate_test ...................***Failed    0.20 sec
      Start  5: imager_test
 5/13 Test  #5: imager_test ......................   Passed    0.91 sec
      Start  6: jones_test
 6/13 Test  #6: jones_test .......................***Failed    0.14 sec
      Start  7: math_test
 7/13 Test  #7: math_test ........................***Failed    0.55 sec
      Start  8: mem_test
 8/13 Test  #8: mem_test .........................***Failed    0.95 sec
      Start  9: sky_test
 9/13 Test  #9: sky_test .........................***Exception: SegFault  0.35 sec
      Start 10: station_test
10/13 Test #10: station_test .....................***Exception: SegFault  0.16 sec
      Start 11: telescope_test
11/13 Test #11: telescope_test ...................***Failed    0.10 sec
      Start 12: utility_test
12/13 Test #12: utility_test .....................   Passed    0.07 sec
      Start 13: vis_test
13/13 Test #13: vis_test .........................   Passed    3.66 sec

38% tests passed, 8 tests failed out of 13

Total Test time (real) =   7.20 sec

The following tests FAILED:
	  3 - convert_test (Failed)
	  4 - correlate_test (Failed)
	  6 - jones_test (Failed)
	  7 - math_test (Failed)
	  8 - mem_test (Failed)
	  9 - sky_test (SEGFAULT)
	 10 - station_test (SEGFAULT)
	 11 - telescope_test (Failed)
Errors while running CTest
```

**Comment by fdulwich** [comment]
It might be worth checking if this is now a problem with the installation of CUDA on that system. From the build directory, could you try running `./apps/oskar_system_info` and see if an error is reported.

**Comment by fdulwich** [comment]
(I should also add that the command is `ctest` on its own, or `ctest --verbose` to see more output. The square brackets around `--verbose` just mean that the flag is optional, so you shouldn't use those on the command itself.)

**Comment by aishrimc** [comment]
As you rightly pointed out, there was some problem with the CUDA installation. Uninstall and re-install from scratch solved the problem. Now `ctest --verbose` is showing `100% tests passed, 0 tests failed out of 13`. Thank you. I should mention here that there was a problem with finding libQt (in the `cmake ..` step when the Anaconda Python executable was the default python. Reverting to /usr/bin/python solved the problem.
