### ISSUE TITLE
Core dump on imager with w-proj algorithm while converting

### ISSUE THREAD

**Issue by srokicki** [OxfordSKA/OSKAR#32]
I've tried using the imager with the w-projection algorithm. I've observed a core dump in the function "oskar_convert_station_uvw_to_baseline_uvw" located in oskar/convert/src/oskar_convert_station_uvw_to_baseline_uvw.c

After investigating a bit, it appears that the convert function is called from line 233 of file "private_imager_read_coords.c" without a proper allocation for arrays uu, vv, ww.
I've added those lines at line 226 of this file : 
```
        /* Need to allocate uu, vv and ww */        
	oskar_mem_realloc(uu, num_baselines*num_times, status);
	oskar_mem_realloc(vv, num_baselines*num_times, status);
	oskar_mem_realloc(ww, num_baselines*num_times, status);
```
It seems to work better now.
I'm not sure whether this is the correct place to allocate. Other calls to the convert function always have the uu, vv and ww arrays already allocated.

Regards, 
Simon Rokicki

**Comment by fdulwich** [comment]
Thank you very much for spotting this and reporting it! Yes, you're quite right, and your fix was also in the right place - well done for tracking it down, and sorry for missing that. Hopefully it should be resolved now.
