### ISSUE TITLE
OpenCL GPU failed on M1 Macs

### ISSUE THREAD

**Issue by sjtuzyk** [OxfordSKA/OSKAR#38]
Hi Team,

We want to report an issue with the current version of OSKAR on the M1-based Macs. OSKAR could not use the GPU onboard while runs fine with the CPUs when installed successfully. We tried both the direct installation from the DMG file and the build-from-source approach. Although building OSKAR through the native ARM compiler failed (not surprisingly), building it via the ROSETTA 2 emulator did work. But we are getting the error `buildComputeProgram: cl2Metal failed clBuildProgram error (code -11)` when trying to let OSKAR use GPU. Looking online, it seems other programs also have this issue on M1 macs.

Did you guys try to run OSKAR with the M1 Macs? Not sure if there is a solution to this error. It would be great to get OSKAR to use the M1 GPUs, and a lot of people may benefit from the solution.

Please see the full log below.

**Comment by ChenxiSSS** [comment]
Hi Team,

We are happy to confirm that the current build 2.8.0-dev16 works fine on the M1 soc, as we tested it successfully both on 7-core M1 Macbook Air and 8-core Mac Mini.

However, the speed is not as fast as we expected. Using our standard simulation test, the M1 is only 61% faster than an Intel Iris Pro Graphics 6200 on an iMac. 

Here is the speed comparison:

| Server        | Computation Time | Write Time | Speed  | GPU Model                    | VRAM            | No. of SP | Base/Boost Freq |
| ------------- | ----------------:| ----------:| ------ | ---------------------------- | ---------------:| ---------:| ---------------:|
| MacMini       | 9433.194 s       | 4.430 s    | 1.607  | Apple M1                     | 16 GB LPDDR4X   | 8?        | 3200 MHz        |
| iMac 21.5     | 15163.754 s      | 7.508 s    | 1.000  | Intel Iris Pro Graphics 6200 | 1536 MB         | 384       | 300/1100 MHz    |
